Repository EECE3093C/team-project-du, pull requests merged in 2023-04, with the labels that each got.

#64 Improve the directory structure, naming conventions #34
  doc/Iteration3/EECE3093C_Presentation.pdf
Labels: bug, documentation

#70 Create a Sign In modal on a website
  src/FrontEnd/Sign_in_modal/App.vue
  src/FrontEnd/Sign_in_modal/SignInModal.vue
Labels: new feature

#72 Cornucopia website
  src/FrontEnd/WebAppSemi/.browserslistrc
  src/FrontEnd/WebAppSemi/.gitignore
  src/FrontEnd/WebAppSemi/babel.config.js
  src/FrontEnd/WebAppSemi/jsconfig.json
  src/FrontEnd/WebAppSemi/package-lock.json
  src/FrontEnd/WebAppSemi/package.json
  src/FrontEnd/WebAppSemi/public/favicon.ico
  src/FrontEnd/WebAppSemi/public/index.html
  src/FrontEnd/WebAppSemi/src/App.vue
  src/FrontEnd/WebAppSemi/src/assets/logo.png
  src/FrontEnd/WebAppSemi/src/components/Navbar.vue
  src/FrontEnd/WebAppSemi/src/components/PageViewer.vue
  src/FrontEnd/WebAppSemi/src/components/SignIn.vue
  src/FrontEnd/WebAppSemi/src/components/SignInModal.vue
  src/FrontEnd/WebAppSemi/src/components/SwipeableCards.vue
  src/FrontEnd/WebAppSemi/src/main.js
  src/FrontEnd/WebAppSemi/vue.config.js
Labels: new feature

#74 Redundant code in Front-End Removed
  src/FrontEnd/Cornucopia.html
  src/FrontEnd/demoSwipePage/style.css
  src/FrontEnd/demoSwipePage/swipe.html
  src/FrontEnd/demoSwipePage/swipe.js
  src/FrontEnd/vue app/index.html
Labels: documentation
